name: Create Release Candidate

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release-candidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - name: Check tags
        shell: bash
        run: git fetch origin --tags
      - name: Calculate version bump
        id: commitizen
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ steps.commitizen.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}