name: Create Release Candidate

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-candidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #   ref: develop
      - name: Check tags
        shell: bash
        run: |
          git fetch origin --tags
          mkdir -p ${{ runner.temp }}
      - name: Calculate version bump
        id: commitizen
        uses: commitizen-tools/commitizen-action@master
        with:
          push: false
          changelog_increment_filename: body.md
      - name: Create release PR
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: release/${{ steps.commitizen.outputs.version }}
          labels: release
          delete-branch: false
          title: "Release v${{ steps.commitizen.outputs.version }}"
          body-path: docs/* # prevents body.md from being committed