name: Create GitHub release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release-candidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to get tags
      - name: Calculate version bump
        id: commitizen
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: ${{ steps.commitizen.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Backmerge to develop
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "noreply@mercedes-benz.com"
          git fetch origin develop
          git checkout develop
          git merge origin/main -X ours --no-edit || exit 1
          git push origin develop