name: Create Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to get tags
          token: ${{ secrets.GH_PAT }}
      - name: Calculate version bump
        id: commitizen
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: ${{ steps.commitizen.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0 # required to get tags
          token: ${{ secrets.GH_PAT }}
      - name: Backmerge to develop
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "noreply@mercedes-benz.com"
          git merge ${{ steps.commitizen.outputs.version }} -X ours
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
